title: "Ravi Learns"
description: "My Learnings • Engineering • AI • Leadership • Experiments"
theme: jekyll-theme-minimal
author: "Ravi N"

# Navigation links
nav:
  - name: "Blog"
    link: /
    posts:
      - name: "Cursor vs Anti-Gravity"
        link: /blog/cursor_vs_anti_gravity
        topics: ["AI & LLMs", "Engineering"]
  - name: "Introduction"
    link: /introduction
  - name: "Disclaimer"
    link: /disclaimer

markdown: kramdown
