title: "Ravi Learns"
description: "My Learnings • Engineering • AI • Leadership • Experiments"
theme: jekyll-theme-minimal
author: "Ravi Kiran Nukala"

# Navigation links
nav:
  - name: "Home"
    link: /
  - name: "Introduction"
    link: /introduction
  - name: "Blog"
    link: /blog

markdown: kramdown
