title: "Ravi Learns"
description: "My Learnings • Engineering • AI • Leadership • Experiments"
theme: jekyll-theme-minimal
author: "Ravi Kiran Nukala"
linkedin: "nukalaravi"

# Navigation links
nav:
  - name: "Home"
    link: /
  - name: "Introduction"
    link: /introduction
  - name: "Blog"
    link: /blog
    posts:
      - name: "Cursor vs Anti-Gravity"
        link: /blog/cursor_vs_anti_gravity
        topics: ["AI & LLMs", "Engineering"]

markdown: kramdown
